Algoritmo "ManzanoPag41Ex4k"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Obama
// Descrição   : Ler um valor e apresentá-lo apenas se o valor não for maior que 3
// Autor(a)    : Vitor B
// Data atual  : 13/04/2025
Var

   numero:inteiro

Inicio

   escreva("Digíte um número:")
   leia(numero)

   se nao (numero > 3) entao
      escreva(numero)
   fimse


Fimalgoritmo