Algoritmo "ManzanoPag41Ex4i"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Obama
// Descrição   : Ler um número inteiro e apresentar se o número é par ou impar
// Autor(a)    : Vitor B
// Data atual  : 13/04/2025
Var

   numero:inteiro

Inicio

   escreva("Digíte um número:")
   leia(numero)
   
   se (numero % 2 = 0) entao
      escreva(numero, " é um número par")
   senao
      escreva(numero, " é um número impar")
   fimse


Fimalgoritmo