Algoritmo "ManzanoPag50Exa"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Obama
// Descrição   : Apresentar os quadrados dos números de 15 á 200
// Autor(a)    : Vitor B
// Data atual  : 26/03/2025
Var

   numero:inteiro
   quadrado:real

Inicio

   repita
      quadrado<- numero*numero
      escreval("Quadrado de ", numero, " é ", quadrado)
      numero<- numero + 1
   ate numero > 200


Fimalgoritmo