Algoritmo "Ex12FACCATFahrenheitParaCelsius"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Obama
// Descrição   : Ler temperatura em fahrenheit e converter para celsius
// Autor(a)    : Vitor B
// Data atual  : 19/03/2025
Var

 grausF,grausC:real

Inicio

escreva("Digíte a temperatura em fahrenheit: ")
leia(grausF)

grausC<-(grausF-32)/9*5

escreva("O valor de ", grausF, " graus fahrenheit em graus celsius é: ", grausC)


Fimalgoritmo