Algoritmo "Ex15FACCATPositivoNegativo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Obama
// Descrição   : Ler um valor e escrever se é positivo ou negativo, considerando que 0 é positivo
// Autor(a)    : Vitor B
// Data atual  : 19/03/2025
Var

valor:intei    ro

Inicio

   escreva("Digíte um valor: ")
   leia(valor)

   se valor < 0 entao
      escreva(valor, " é negativo")
   senao
      escreva(valor, " é positivo")
   fimse

Fimalgoritmo