Algoritmo "ManzanoPag66Ex01f"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Obama
// Descrição   : Apresentar todos os números divisiveis por 4 na escla de 4 a 200
// Autor(a)    : Vitor B
// Data atual  : 28/03/2025
Var

   numero:inteiro

Inicio

   numero<- 4

   para numero de 4 ate 200 passo 1 faca
        se (numero % 4 = 0) entao
           escreval(numero)
        fimse
        numero<- numero + 1
   fimpara


Fimalgoritmo