Algoritmo "ManzanoPag66Ex01c"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Obama
// Descrição   : Apresentar a soma dos números entre 1 e 100
// Autor(a)    : Vitor B
// Data atual  : 28/03/2025
Var

   numero,somatorio:inteiro

Inicio

   somatorio<- 2
   numero<- 1

   para numero de 1 ate 99 faca
      somatorio<- somatorio + numero
      escreval(numero, " + ", numero+1, " = ", somatorio)
      numero<- numero + 1
   fimpara


Fimalgoritmo