Algoritmo "ManzanoPag66Ex01e"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Obama
// Descrição   : Apresentar todos os números impares na escla de 1 a 20
// Autor(a)    : Vitor B
// Data atual  : 28/03/2025
Var

   numero:inteiro

Inicio

   numero<- 1

   para numero de 1 ate 20 passo 1 faca
        se nao (numero %2 = 0) entao
           escreval(numero)
        fimse
        numero<- numero + 1
   fimpara


Fimalgoritmo