Algoritmo "ManzanoLista05Ex01A"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Obama
// Descrição   :
// Autor(a)    : Vitor B
// Data atual  : 28/03/2025
Var

   contador, quadrado:inteiro

Inicio

   para contador de 15 ate 200 passo 1 faca
        quadrado<- contador * contador
        escreval("Quadrado de ", contador, " = ", quadrado)
   fimpara


Fimalgoritmo