Algoritmo "ManzanoLista05Ex01C"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Obama
// Descrição   : Apresentar todos os números divíveis por 4 que sejam menores que 200
// Autor(a)    : Vitor B
// Data atual  : 28/03/2025
Var

   contador:inteiro

Inicio

   para contador de 1 ate 200 passo 1 faca
      se (contador % 4 = 0) entao
         escreval(contador)
      fimse
      contador<- contador + 1
   fimpara


Fimalgoritmo