Algoritmo "ManzanoLista05Ex01B"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Obama
// Descrição   :
// Autor(a)    : Vitor B
// Data atual  : 28/03/2025
Var

   contador1, soma:inteiro

Inicio

   para contador1 de 1 ate 500 passo 1 faca
        se contador1%2 = 0 entao
           soma <- soma + contador1
           escreval(contador1)
        fimse
   fimpara
   
   escreva(soma)

Fimalgoritmo